### ISSUE TITLE
question about torchsummary

### ISSUE THREAD

**Issue by DLsnowman** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#13]
hello, in line 102:torchsummary.summary(model_test, input_size=(3, 128, 128))
I get a error: Error in dlopen or dlsym: libnvrtc.so.10.0: cannot open shared object file: No such file or directory. 
Is the problen about version of torchsummary?

**Comment by bigmb** [comment]
It can  be due to its version. Which one are you using?

**Comment by DLsnowman** [comment]
Mine is torchsummary 1.5.1, pytorch 1.2.0. 
I can run:  summary(torchvision.models.vgg11().cuda(), input_size=(3, 128, 128)). 
but can not summary() the U_Net instance whose class is written in Models.py file.

**Comment by DLsnowman** [comment]
When I use torch.cat() without cuda():
a = torch.tensor(np.random.random((3, 5)))
b = torch.tensor(np.random.random((6, 5)))
c = torch.cat((a, b), 0)
There is no error.
When I use cuda():
a = torch.tensor(np.random.random((3, 5))).cuda()
b = torch.tensor(np.random.random((6, 5))).cuda()
c = torch.cat((a, b), 0)
The error happens: 
RuntimeError: Error in dlopen or dlsym: libnvrtc.so.10.0: cannot open shared object file: No such file or directory

**Comment by DLsnowman** [comment]
the problem is about the version of pytorch 1.2.0
I install pytorch1.1.0. 
The error disappears.

**Comment by bigmb** [comment]
Pytorch 1.1.0  just got stable, I suggest dont shift to 1.2.0 right now. 
I looked online into the issue. Couldn't find much on it.
