### ISSUE TITLE
where is the dataset?

### ISSUE THREAD

**Issue by Halleyawoo** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#16]

**Comment by bigmb** [comment]
Hello, 

The dataset I have used is from Alzheimer’s Disease Neuroimaging Initiative.
http://adni.loni.usc.edu/

**Comment by Halleyawoo** [comment]
Thank you very much！

**Comment by Halleyawoo** [comment]
Hello,

I am a little confused of ANDI dataset. There are too much data and I can't find 'new_3C_I_ori/','new_3C_L_ori/','test_new_3C_I_ori/0131_0009.png',test_new_3C_L_ori/0131_0009.png' .Can you give me a more specific link of your dataset or upload it?

Thank you very much!

**Comment by bigmb** [comment]
All these dataset have been created using different techniques from the main dataset.
It wouldn't be possible to share the dataset as it's more than 5 GB I think.
