### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Halleyawoo** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#19]
HI!
very nice work!

I have no idea of this dataset. The link is as follows:

https://ida.loni.usc.edu/pages/access/search.jsp?tab=collection&loginKey=1568321853435385522&userEmail=949774840%40qq.com&project=ADNI&page=DOWNLOADS&subPage=IMAGE_COLLECTIONS

It just have .nii projects, I can not find .png which you are using in the test_image and test_label. 
Could you please give me a very specific link? I'll very appreciate about it!

**Comment by bigmb** [comment]
I have made my png from the MRI files. 
There is a .py file called 2d from 3d in the repo. 
Have a look at it.

**Comment by Halleyawoo** [comment]
okay, thanks for your reply!

**Comment by Halleyawoo** [comment]
please don't close it now, maybe I 'll have some problems lately.
lol 
thank you!

**Comment by bigmb** [comment]
Sure. No problem. You can even write to me on malav.b93@gmail.com.

**Comment by Halleyawoo** [comment]
Hello！
I met a problem which says:

RuntimeError: output with shape [1, 96, 96] doesn't match the broadcast shape [3, 96, 96]

I referred to online tutorials, change the sentence :
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])]) 

 into another sentence :
transform = transforms.Compose([
     transforms.ToTensor(),
     transforms.Lambda(lambda x: x.repeat(3,1,1)),
     transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
 ])

But it is still the same error. Could you tell me why?
Thx very much!

**Comment by bigmb** [comment]
Its probably because you are providing a 1D input to the expected 3D tensor. 
try :
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=[0.5], std=[0.5])])

But what is your input to the transformation?

**Comment by Halleyawoo** [comment]
Thanks for your reply.
 I tried this method, and 
 transform = transforms.Compose([
&nbsp;&nbsp;&nbsp;&nbsp; transforms.ToTensor(),
&nbsp;&nbsp;&nbsp;&nbsp; transforms.Lambda(lambda x: x.repeat(3,1,1)),
&nbsp;&nbsp;&nbsp;&nbsp; transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
&nbsp;])
 &nbsp;
 but it is still not work.
 &nbsp;
 My input is shown in the compressed file.
 EDAC_RawData is the original dataset, Image is the generated data after I run 2d_from_3d.py.
————————————————
版权声明：本文为CSDN博主「山水@有相逢」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/weixin_43159148/article/details/88778371
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Malav Bateriwala"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年1月1日(星期三) 晚上11:33
 收件人:&nbsp;"bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets"<Unet-Segmentation-Pytorch-Nest-of-Unets@noreply.github.com&gt;;
 抄送:&nbsp;"宇文畅"<949774840@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets] About the dataset (#19)

 

 
Its probably because you are providing a 1D input to the expected 3D tensor.
try :
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=[0.5], std=[0.5])])
 
But what is your input to the transformation?

**Comment by bigmb** [comment]
What is the shape of the input given to datasets?
Can you share those details?

and the shape of the output of the 2d_from_3d file that you are creating?

**Comment by Halleyawoo** [comment]
The processed image pixels are 128 by 128.
 And the attached is my original dataset.
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Malav Bateriwala"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年1月2日(星期四) 晚上9:06
 收件人:&nbsp;"bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets"<Unet-Segmentation-Pytorch-Nest-of-Unets@noreply.github.com&gt;;
 抄送:&nbsp;"宇文畅"<949774840@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets] About the dataset (#19)

 

 
What is the shape of the input given to datasets?
Can you share those details?
 
and the shape of the output of the 2d_from_3d file that you are creating?

**Comment by Halleyawoo** [comment]
Sorry, my original dataset is too large(1.4GB), I just failed to send it to you. 
I have uploaded my data set to baidu cloud, the link is here, can you download it and have a look
 https://pan.baidu.com/s/1tsJsHHDZmspS7mtP4SHAbg
  ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Malav Bateriwala"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年1月2日(星期四) 晚上9:06
 收件人:&nbsp;"bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets"<Unet-Segmentation-Pytorch-Nest-of-Unets@noreply.github.com&gt;;
 抄送:&nbsp;"宇文畅"<949774840@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets] About the dataset (#19)

 

 
What is the shape of the input given to datasets?
Can you share those details?
 
and the shape of the output of the 2d_from_3d file that you are creating?

**Comment by husheng876** [comment]
> Its probably because you are providing a 1D input to the expected 3D tensor.
> try :
> transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=[0.5], std=[0.5])])
> 
> But what is your input to the transformation?

i have tried this solution but didn't solve the problem.And my input data and mask are 1D
