### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by tearsness** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#23]
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by bigmb** [comment]
Is this the whole error?Where do you face this issue? 
Any particular part of the code?
