### ISSUE TITLE
How to test single image

### ISSUE THREAD

**Issue by JasonChenhx** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#25]
I want to know the code of how to test single image.
Thanks

**Comment by bigmb** [comment]
You mean after the weights are trained?
I couldn't get your question properly.

**Comment by JasonChenhx** [comment]
> 
> 
> You mean after the weights are trained?
> I couldn't get your question properly.

I mean that I have got the model.pth after train, I want to test single image to see the performance of the result.
Thanks

**Comment by bigmb** [comment]
During the training its saved in the pred folder.

And after training if you just want to test a single file again. Then you will have to call line 408 (model loading ) and then set it to eval (line 412) .
After that follow the commands given in the line 290-306.

**Comment by JasonChenhx** [comment]
Thank you very much!
Your answer is of great help to me!
Thanks again!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Malav Bateriwala"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 下午2:54
收件人:&nbsp;"bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets"<Unet-Segmentation-Pytorch-Nest-of-Unets@noreply.github.com&gt;;
抄送:&nbsp;"JasonChenhx"<chx880324@163.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets] How to test single image (#25)




During the training its saved in the pred folder.
 
And after training if you just want to test a single file again. Then you will have to call line 408 (model loading ) and then set it to eval (line 412) .
 After that follow the commands given in the line 290-306.
