### ISSUE TITLE
how many memory does the Nest Unet require when dealing with 3D image?

### ISSUE THREAD

**Issue by Kay-Shaw** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#27]
I modified the network to deal with 3D medical image with a GPU(12G), but it feeds back "CUDA out of memory. Tried to allocate 1.50 GiB (GPU 0; 11.91 GiB total capacity; 9.84 GiB already allocated; 1.45 GiB free; 21.18 MiB cached)"  

so how many GPU memory does the Nest Unet require when dealing with 3D image?

**Comment by bigmb** [comment]
Nest Unet requires a lot of memory. (But less than R-Attention-CNN Unet)
Whats the size of your input?
Also are you using patches or complete 3D image as an input?

**Comment by Kay-Shaw** [comment]
i used resized 128^3 image as input, maybe I should try smaller size, but that would lead to poor performance

**Comment by bigmb** [comment]
Try it with a smaller size and check if the nested unet works. If it works , then the current issue is due to allocation of memory.
