### ISSUE TITLE
where is the data?

### ISSUE THREAD

**Issue by zz10001** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#3]

**Comment by bigmb** [comment]
I can't upload my dataset. It's from ADNI.

**Comment by zz10001** [comment]
> I can't upload my dataset. It's from ADNI.

much obligated,and i think you can paste the link about where the data to download(like data preparation).thank you once for your work!

**Comment by bigmb** [comment]
http://adni.loni.usc.edu/
This is the link. Thanks man. :)

**Comment by zz10001** [comment]
you are welcome!:)

**Comment by Halleyawoo** [comment]
> you are welcome!:)
hi, can you give me a more specific link of the author's dataset? I can not find the t_data, l_data and so on. thank you very much!

**Comment by bigmb** [comment]
> > you are welcome!:)
> > hi, can you give me a more specific link of the author's dataset? I can not find the t_data, l_data and so on. thank you very much!

@Halleyawoo my dataset is quite specific for a particular region of the brain. It has been taken from the adni dataset only and then given to me by my supervisor.  Do you want a dataset for alzheimers detection?
