### ISSUE TITLE
The color of label and a suggestion

### ISSUE THREAD

**Issue by xumeng19** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#38]
Hello, the author, first of all, thank you very much for the code. Excuse me, the label of the picture I input is binary. Why is the predicted picture not binary? Where do I need to change the color of the forecast picture? There is also a small suggestion, can you make the code more readable?

**Comment by bigmb** [comment]
It just had more channels. Try to visualize each channel, and you will get your required output. 
I think there will be a 4 channel prediction image. 

If you have some help in understanding the code just let me know. I did try to comment on it at that time. 
But to restructure it will take some time and I have other commitments right now. 
Also if you do it, then I will be happy to merge and give you the credits.

**Comment by xumeng19** [comment]
I'm sorry, I'm just a beginner. Thank you very much for your answer, but I can't help you with my ability

**Comment by ppjerry** [comment]
import skimage.io as io
using io.imsave instead of the plot.imsave when saving images

**Comment by xumeng19** [comment]
> 保存图像时，使用io.imsave而不是plot.imsave将skimage.io作为io导入

OK, thank you. I'll try
