### ISSUE TITLE
ValueError: Shape mismatch: im1 and im2 must have the same shape.

### ISSUE THREAD

**Issue by sunny0414** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#42]
How  to save this problem?ValueError: Shape mismatch: im1 and im2 must have the same shape.

**Comment by bigmb** [comment]
@sunny0414 Can you be a little more specific?
Are you facing issue in attention unet?
If not, I suggest you check the shape of your images just to be sure.

**Comment by sunny0414** [comment]
Thanks for you repply,I have solved the problem.

**Comment by findlayr** [comment]
Hi.
I met the same error
could you please tell me how to solve the  problem?
Thank you.

**Comment by findlayr** [comment]
@sunny0414 
Hi.
I met the same error
could you please tell me how to solve the problem?
Thank you.
