### ISSUE TITLE
Dice Score and the different and connection with MIou?

### ISSUE THREAD

**Issue by sunny0414** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#43]
Hello ,thanks for you code.I have confuse about evaluation metrics,and what is the dice score ? It different and connection with MIouU

**Comment by bigmb** [comment]
Dice Score:  2 * the Area of Overlap divided by the total number of pixels in both images.
IoU: It's an evaluation metric used to measure the accuracy of an annotation on a particular task!

I think you should refer to this page for an even deeper understanding and also why Dice is used in medical.
https://towardsdatascience.com/metrics-to-evaluate-your-semantic-segmentation-model-6bcb99639aa2#:~:text=3.,of%20pixels%20in%20both%20images.&text=They%20are%20positively%20correlated%2C%20meaning,other%20will%20say%20the%20same.
