### ISSUE TITLE
Some meaningless parameters

### ISSUE THREAD

**Issue by husheng876** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#44]
There are some meaningless parameters in this system that I found it make no sense. For example,i_valid in pytorch_run.py file.it was used in the part of early stopping, but it makes no effect. The judge of i_valid's value was marked out.
And I don't understand the meaning of "epoch_valid " in pytorch_run.py file. Why the value of it is "epoch-2"?Could you help me understand those codes? Thank you.

**Comment by bigmb** [comment]
Before I was using the i_valid and epoch_valid = epoch-2 for some kind of early stopping.
If you chekc the code there is some commented part over there and you will see different if loops with different value input.
