### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by zhou-rui1** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#46]
Hi, the code is awsome, but how can I fix this error, since I have change my image from 4 channels,to RGB
```
RuntimeError: output with shape [1, 530, 500] doesn't match the broadcast shape [3, 530, 500]
```
With reagrds, any help would be so grateful!

**Comment by bigmb** [comment]
Thank you.
Can you let me know where you are facing this issue? ( in model or preprocessing )

**Comment by zhou-rui1** [comment]
Thanks a lot! It is in model , when the label is gray image it occurs
```
 File "pytorch_run.py", line 302, in <module>
    s_label = data_transform(im_label)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 226, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py", line 284, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 96, 96] doesn't match the broadcast shape [3, 96, 96]
```

**Comment by bigmb** [comment]
Can you look at this issue?
https://github.com/bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets/issues/37
Also, change the out_ch=1 (that's the output channel you will be getting as an output.)

**Comment by zhou-rui1** [comment]
So appreciated for your guidance, but the case a little different. Now I have the following set：
`torchvision.transforms.Normalize((0.5,), (0.5,))`
`im_tb = Image.open(test_image).convert('RGB')`
`def __init__(self, in_ch=3, out_ch=1):`
But it still get this :
`File "pytorch_run.py", line 265, in <module>
    lossT = calc_loss(y_pred, y)     # Dice_loss Used
  File "/content/Unet-Segmentation-Nest-of-Unets/losses.py", line 32, in calc_loss
    bce = F.binary_cross_entropy_with_logits(prediction, target)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2580, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([4, 2, 96, 96])) must be the same as input size (torch.Size([4, 1, 96, 96]))`
How can I make both of them work?
With regards

**Comment by bigmb** [comment]
Currently, I am seeing only one issue that you are facing with the loss function.
Can you check the size of the input to the  `y_pred and y`?

I think the shape of the data is getting mismatched somewhere due to preproccesing.

**Comment by zhou-rui1** [comment]
Thanks a lot, that problem solved, but why got this with 3 channels input？
`[Errno 99] Cannot assign requested address
Given groups=1, weight of size [64, 3, 3, 3], expected input[3, 1, 128, 128] to have 3 channels, but got 1 channels instead
Error occurs, No graph saved
Traceback (most recent call last):
  File "pytorch_run.py", line 176, in <module>
    writer1.add_graph(model_test, model_test(torch.randn(3, 3, 128, 128, requires_grad=True)))`
and seems that the tensorboardX can not work well?
With regards,

**Comment by bigmb** [comment]
If you are planing to use tensorboardx it's going to be difficult.
Currently tensorboardx doesnt support skip connections. If it's a simple network it works.
I havnt checked if the current version is upgraded for the same. I will have a look at that next weekend.
Is the main code working for you?
