### ISSUE TITLE
Test Models on Test Image Folder

### ISSUE THREAD

**Issue by PrinceEAdjei** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#47]
I would like to test the trained models on my test image folder. It seems the code does not do that. Rather, some pre-selected images are iteratively evaluated per each epoch during training. 

I would like to use the already trained model to test my Test dataset and generate segmentation maps.

**Comment by bigmb** [comment]
I don't think I am following your question.
If you are talking about testing the model on the test folder, you can check the code in pytorch_run.py from line 418. Because from that part, the testing starts of the model. 
Before that, there is also a validation of the training images.

**Comment by PrinceEAdjei** [comment]
Thank you. I double-checked the code. Works fine now. 

I appreciate so much!
