### ISSUE TITLE
hello,is  label a 3 channels image?

### ISSUE THREAD

**Issue by CasonTsai** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#51]
i got this mistake ,it the label a 3 channels image?not a single channle image
![image](https://user-images.githubusercontent.com/18262642/130898650-ba065733-46b2-4c24-bd82-5067adc93089.png)

**Comment by Alex28132** [comment]
> my input image is 3 channels,label image is single channel

Sir, have you solved this problem? I have also encountered this problem
