### ISSUE TITLE
dim

### ISSUE THREAD

**Issue by giter915** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#55]
File "F:\some_project\Unet-Segmentation-Pytorch-Nest-of-Unets-master\Unet-Segmentation-Pytorch-Nest-of-Unets-master\Models.py", line 102, in forward
    d5 = torch.cat((e4, d5), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 61 but got size 60 for tensor number 1 in the list.

**Comment by bigmb** [comment]
Whats the data shape?
Make sure its in muliple of 2^4. 
Or reduce the depth of the model.
(You can check other closed issue for this too.)
