### ISSUE TITLE
Data set

### ISSUE THREAD

**Issue by yiseni** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#58]
Hello, I am not quite clear about the meaning of the files in each folder for the data set. Could you please give me an example?

**Comment by bigmb** [comment]
Hey @yiseni ,
Here files in each folder means images in each folder.
Dir : ./train_images 
Image: ./train_images/img_*

**Comment by yiseni** [comment]
t_data = '/flush1/bat161/segmentation/New_Trails/venv/DATA/new_3C_I_ori/'
l_data = '/flush1/bat161/segmentation/New_Trails/venv/DATA/new_3C_L_ori/'
test_image = '/flush1/bat161/segmentation/New_Trails/venv/DATA/test_new_3C_I_ori/0131_0009.png'
test_label = '/flush1/bat161/segmentation/New_Trails/venv/DATA/test_new_3C_L_ori/0131_0009.png'
test_folderP = '/flush1/bat161/segmentation/New_Trails/venv/DATA/test_new_3C_I_ori/*'
test_folderL = '/flush1/bat161/segmentation/New_Trails/venv/DATA/test_new_3C_L_ori/*'
I want to know the specific meaning of each path. Could you please explain the structure diagram of the data set in detail? Thank you very much

**Comment by bigmb** [comment]
- Trainset:

>         training_images_folder: path to your training images folder
>         training_labels_folder: path to your training labels folder

```
  Test_image (this was created to get each epoch results in folder) : path to test image
  Test_label (label of the test image used to created each epoch results) path to label of the test image
```

- Testset:

```
   testing_image_folder: path to your testing images folder 
   testing_labels_folder: path to your testing images folder
```

All these are not given in one location because my data was quite small and everything was quite segerated. But if you want you can update the flow and send me a pull request.

**Comment by yiseni** [comment]
Ok thank you very much
