### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 38348, 20180, 30224, 8512, 38232, 19588, 39276, 10048) exited unexpectedly

### ISSUE THREAD

**Issue by RaylinLee** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#68]
Hello, I ran your program and encountered this issue. I'm not sure if it's due to a problem with the categorization of the dataset. Do you have any suggestions for solving this?
best regard,
Ray
![image](https://github.com/bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets/assets/152707376/335a2b5f-96da-43a0-8c4e-cb3385eb293d)

**Comment by bigmb** [comment]
Try running it without num_workers and reducing the batch_size.
